name: CI

on:
  push:
    paths:
      - '.SRCINFO'
      - 'PKGBUILD'
  workflow_dispatch:
    inputs:
      version:
        description: 'Upstream synced version'
        default: ''
        required: true

jobs:
  build:
    name: Build package
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4

      - name: Build & validate package
        uses: datakrama/archlinux-package-action@v1

  release:
    name: Release package
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4
        with:
          persist-credentials: false
          fetch-depth: 0
          ref: aur

      - run: |
          if [[ -z "${{ github.event.inputs.version }}" ]]; then
            COMMIT_MESSAGE="Update AUR package"
          elif [[ -n "${{ github.event.inputs.version }}" ]]; then
            COMMIT_MESSAGE="feat: bump to ${{ github.event.inputs.version }}"
          fi
          git checkout main PKGBUILD .SRCINFO
          git config --local user.name ${{ secrets.GIT_USERNAME }}
          git config --local user.email ${{ secrets.GIT_EMAIL }}
          git add PKGBUILD .SRCINFO
          git commit -m "$COMMIT_MESSAGE"

      - name: Push changes to GitHub
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: aur

      - name: Push changes to AUR
        uses: datakrama/push-aur-action@v1
        with:
          pkgname: ${{ github.event.repository.name }}
          git_username: ${{ secrets.GIT_USERNAME }}
          git_email: ${{ secrets.GIT_EMAIL }}
          private_ssh_key: ${{ secrets.AUR_PRIVATE_SSH_KEY }}
